// flow-typed signature: 0c103a5c0173c56148fd7759a73e9eb0
// flow-typed version: <<STUB>>/licensor_v^4.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'licensor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'licensor' {
  declare module.exports: any;
}
